version: '3.8'

services:
  php_fpm:
    build:
      context: ./docker/php
    container_name: php_fpm
    volumes:
      - .:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - .:/var/www
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: crypto_app
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-pB0jfkd00@SEE", "-e", "SELECT 1"]
      interval: 10s
      timeout: 4s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
